# Python Imports
# Third-Party Imports
# Project Imports


MAX_VOLUME_NORMALISED: float = 0.10
MIN_VOLUME_NORMALISED: float = 0.0
DEFAULT_VOLUME_NORMALISED: float = (MAX_VOLUME_NORMALISED - MIN_VOLUME_NORMALISED) / 2
DEFAULT_VOLUME_INCREMENT_NORMALISED: float = DEFAULT_VOLUME_NORMALISED / 10
